export const issues = [
  {
    id: 1,
    title: "Read Something",
    description: "Read Something for school project",
    boardId: 329840982,
    column: "todo",
  },
  {
    id: 2,
    title: "Read Something",
    description: "Read Something for school project",
    boardId: 329840982,
    column: "todo",
  },
  {
    id: 3,
    title: "Read Something",
    description: "Read Something for school project",
    boardId: 329840982,
    column: "todo",
  },
  {
    id: 4,
    title: "Read Something",
    description: "Read Something for school project",
    boardId: 329840982,
    column: "in progress",
  },
  {
    id: 5,
    title: "Read Something",
    description: "Read Something for school project",
    boardId: 329840982,
    column: "in progress",
  },
  {
    id: 6,
    title: "Read Something",
    description: "Read Something for school project",
    boardId: 329840982,
    column: "in progress",
  },
  {
    id: 7,
    title: "Read Something",
    description: "Read Something for school project",
    boardId: 329840982,
    column: "done",
  },
  {
    id: 8,
    title: "NO BOARD",
    description: "Read Something for school project",
    boardId: 3298409824,
    column: "done",
  },
  {
    id: 9,
    title: "NO BOARD",
    description: "Read Something for school project",
    boardId: 3298409824,
    column: "done",
  },
  {
    id: 10,
    title: "NO BOARD",
    description: "Read Something for school project",
    boardId: 3298409824,
    column: "done",
  },
];
